name: deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: siteground-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Start an ssh-agent and load your private key (handles passphrase)
      - name: Load SSH key (with passphrase)
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SG_SSH_KEY }}     # your PRIVATE key
          ssh-passphrase:  ${{ secrets.SG_PASSPHRASE }}  # add this secret if your key is encrypted

      # Trust the server host key and do a quick connectivity probe
      - name: Prepare known_hosts & test SSH
        run: |
          set -e
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keyscan -p "${{ secrets.SG_PORT }}" "${{ secrets.SG_HOST }}" >> ~/.ssh/known_hosts 2>/dev/null || true
          ssh -o StrictHostKeyChecking=yes -p "${{ secrets.SG_PORT }}" \
            "${{ secrets.SG_USER }}@${{ secrets.SG_HOST }}" "echo SSH_OK"

      # Deploy with rsync (uses the ssh-agent, so no -i flag needed)
      - name: Deploy via rsync
        run: |
          set -e
          rsync -avz --delete \
            --exclude ".git/" \
            --exclude ".github/" \
            --exclude "node_modules/" \
            -e "ssh -p ${{ secrets.SG_PORT }} -o StrictHostKeyChecking=yes" \
            ./ "${{ secrets.SG_USER }}@${{ secrets.SG_HOST }}:${{ secrets.SG_PATH }}/"

          # Show what landed
          ssh -o StrictHostKeyChecking=yes -p "${{ secrets.SG_PORT }}" \
            "${{ secrets.SG_USER }}@${{ secrets.SG_HOST }}" "ls -la '${{ secrets.SG_PATH }}' | tail -n +1"
