name: Deploy to SiteGround

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: siteground-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH
        env:
          SG_SSH_KEY: ${{ secrets.SG_SSH_KEY }}
          SG_HOST: ${{ secrets.SG_HOST }}
          SG_PORT: ${{ secrets.SG_PORT }}
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "$SG_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -p "$SG_PORT" "$SG_HOST" >> ~/.ssh/known_hosts 2>/dev/null

      - name: Deploy via rsync
        env:
          SG_HOST: ${{ secrets.SG_HOST }}
          SG_PORT: ${{ secrets.SG_PORT }}
          SG_USER: ${{ secrets.SG_USER }}
          SG_PATH: ${{ secrets.SG_PATH }}
        run: |
          rsync -avz --delete \
            --exclude ".git/" \
            --exclude ".github/" \
            --exclude "README.md" \
            -e "ssh -p $SG_PORT -o StrictHostKeyChecking=accept-new" \
            ./ "$SG_USER@$SG_HOST:$SG_PATH/"